#ifndef _GLYPHS_H_
#define _GLYPHS_H_

#define GLYPH_SCREEN_DEPTH_UP 128
#define GLYPH_SCREEN_DEPTH_DOWN 129
#define GLYPH_WINDOW_CLOSE 130
#define GLYPH_WINDOW_DEPTH_UP 131
#define GLYPH_WINDOW_DEPTH_DOWN 132
#define GLYPH_RADIO_BUTTON_OFF 133
#define GLYPH_RADIO_BUTTON_ON 134
#define GLYPH_RADIO_BUTTON_MU 135
#define GLYPH_CHECK_BOX_OFF 136
#define GLYPH_CHECK_BOX_ON 137
#define GLYPH_CHECK_BOX_MU 138
#define GLYPH_SCREEN_FLIP_UP 139
#define GLYPH_SCREEN_FLIP_DOWN 140
#define GLYPH_ARROW_UP 141
#define GLYPH_ARROW_DOWN 142
#define GLYPH_ARROW_LEFT 143
#define GLYPH_ARROW_RIGHT 144
#define GLYPH_CYCLE 145
#define GLYPH_BACKSPACE 146
#define GLYPH_RETURN 147
#define GLYPH_SHIFT 148
#define GLYPH_CAPS_LOCK 149
#define GLYPH_CONTROL 150

#define GLYPH_INTEGRAL 151
#define GLYPH_DERIVATE 152
#define GLYPH_ROOT 153
#define GLYPH_SUM 154
#define GLYPH_PI 155
#define GLYPH_IMAGINARY 156
#define GLYPH_EULER 157
#define GLYPH_RATIONAL 158
#define GLYPH_LUBRACE 159
#define GLYPH_RUBRACE 160
#define GLYPH_LDBRACE 161
#define GLYPH_RDBRACE 162

#endif
